title: Khôi's blog
email: o0khoiclub0o@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where I publish my posts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://o0.khoi.club" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: assets/css/_sass
    style: :compressed

defaults:
  -   
    scope:
      type: posts
    values:
      permalink: /:year/:month/:day/:title

google_analytics_key: UA-93474352-1

# Profile links, leave blank to ignore
social: 
  github: o0khoiclub0o
  linkedin: o0khoiclub0o
  facebook: o0khoiclub0o
